argparse_cfg:
  gpus:
    bind_to: processor_cfg.gpus
    help: number of gpus
  batch_size:
    bind_to: processor_cfg.batch_size
  checkpoint:
    bind_to: processor_cfg.checkpoint
    help: the checkpoint file to load from
    default: 

processor_cfg:
  type: "processor.recognition.test"

  # model setting
  model_cfg:
    type: "models.backbones.DyadicRelationalGCN"
    in_channels: 3
    num_class: 8
    dropout: 0.5
    T: 100
    RAM_encoder_output_channels: 128
    RAM_decoder_output_channels: 8
    edge_importance_weighting: True
    multiply_relative_adjacency: True
    distance_relative_adjacency: True
    graph_cfg:
      layout: "sbu"
      strategy: "spatial"

  # dataset setting
  dataset_cfg:
    type: "feeder.skeleton_feeder.SkeletonFeeder"
    data_path: ./data/SBU/val_data_0.npy
    label_path: ./data/SBU/val_label_0.pkl
    debug: true

  # dataloader setting
  batch_size: 20
  gpus: 2
