argparse_cfg:
  gpus:
    bind_to: processor_cfg.gpus
    help: number of gpus
  batch_size:
    bind_to: processor_cfg.batch_size
  checkpoint:
    bind_to: processor_cfg.checkpoint
    help: the checkpoint file to load from
    default: 

processor_cfg:
  type: "processor.recognition.test"
  checkpoint:

  # model setting
  model_cfg:
    type: "models.backbones.DyadicRelationalGCN"
    in_channels: 3
    num_class: 26
    dropout: 0.5
    T: 300
    RAM_encoder_output_channels: 128
    RAM_decoder_output_channels: 64
    edge_importance_weighting: True
    multiply_relative_adjacency: True
    distance_relative_adjacency: True
    graph_cfg:
      layout: "ntu-rgb+d"
      strategy: "spatial"

  # dataset setting
  dataset_cfg:
    type: "feeder.skeleton_feeder.SkeletonFeeder"
    data_path: ./data/NTU-RGB-D-120/xsub/val_data.npy
    label_path: ./data/NTU-RGB-D-120/xsub/val_label.pkl
    duo_only: True

  # dataloader setting
  batch_size: 20
  gpus: 2
